#!/usr/bin/env bash

# Fail if any commands fails
set -x

# Remove reference snapshots:

readonly scripts_path="$( cd "$(dirname "$0")" ; pwd -P )"
readonly root_directory=`"${scripts_path}/repository-root-path"`
readonly tests_directory="${root_directory}/Tests"
readonly snapshots_directory="__Snapshots__"

cd "${tests_directory}"

dirs=($(find . -type d))
for dir in "${dirs[@]}"; do
    cd "${dir}"
    rm -rf "./${snapshots_directory}/"
    cd "${tests_directory}"
done
