name: test
on: push
jobs:
  build:
    name: test
    runs-on: macOS-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: swift test
        run: |
          # TODO: @CSolanaM macOS tests not passing because CI screen scale factor is 1, local is 2
          # xcodebuild test -destination platform="macOS" -scheme "SkeletonUISnapshotTests"
          xcodebuild test -destination name="Apple TV" -scheme "SkeletonUISnapshotTests"
          xcodebuild test -destination name="Apple TV 4K" -scheme "SkeletonUISnapshotTests"
          xcodebuild test -destination name="iPhone 8" -scheme "SkeletonUISnapshotTests"
          xcodebuild test -destination name="iPhone 11 Pro Max" -scheme "SkeletonUISnapshotTests"
          xcodebuild test -destination name="iPad Pro (12.9-inch) (3rd generation)" -scheme "SkeletonUISnapshotTests"
